{% set name = "phik" %}
{% set version = "0.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/phik-{{ version }}.tar.gz
  sha256: b0674eb829d23290433f718d2360122be804b170ccc807ad9d9a8d1c13985533

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools >=42
    - wheel
    - pybind11 >=2.8.1
    - scikit-build >=0.13.1
    - cmake >=3.16
    - ninja-base
  run:
    - python
    - numpy >=1.18.0
    - scipy >=1.5.2
    - pandas >=0.25.1
    - matplotlib-base >=2.2.3
    - joblib >=0.14.1

test:
  imports:
    - phik
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://phik.rtfd.io
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
  summary: Phi_K correlation analyzer library
  description: |
    Phi_K is a new and practical correlation coefficient based on several
    refinements to Pearson's hypothesis test of independence of two variables.
  doc_url: https://phik.readthedocs.io/
  dev_url: https://github.com/KaveIO/PhiK

extra:
  recipe-maintainers:
    - cbouss
