{% set name = "PhiK" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/d9/27/d4197ed93c26d9eeedb7c73c0f24462a65c617807c3140e012950c35ccf9/phik-{{ version }}.tar.gz
  sha256: cefab72ddd937be6ffe0336ef0fe7ea029c5ae7af0036e2390dc626113adcb25

build:
  number: 0
  noarch: python
  entry_points:
    - phik_trial = phik.entry_points:phik_trial  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.15.4
    - scipy >=1.1.0
    - pandas >=0.23.4
    - matplotlib-base >=2.2.3
    - numba >=0.38.1
    - joblib >=0.14.1

test:
  imports:
    - phik

about:
  home: https://github.com/KaveIO/PhiK
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Phi_K correlation analyzer library
  description: |
    Phi_K is a new and practical correlation coefficient based on several
    refinements to Pearson's hypothesis test of independence of two variables.
  doc_url: http://phik.readthedocs.io/
  dev_url: https://github.com/KaveIO/PhiK

extra:
  recipe-maintainers:
    - philip-khor
