travis:
  secure:
    BINSTAR_TOKEN: koa6Io727oJmF5oBS8lIfdU9+n1yd8Xh1sNcRTgN/mpv6PS/LMoJsXSwJBdjRIzDcaeOFn1nAaS/Im74DUaZRHerI4Hoxa/NU+Hna/N/VmaNzQydHfteXpKTUoFH/0XEveyq47hYKeH5Ht7s/eSGUyX11zoncBIHlfSkWc+Ia3ofTGPv7oEjoSYN0EdQwK88LNPIcmp54LCAQHFMVjCSJsfD8/z7oe4wsmuXRm/ntX7fIVINfLwcFIXq53azhnp2c7RO99TFPPLSOoREqgUE2Ri3g6/p7LqCBy+r4qVj6j5LLDazNPuo9RAR9ZhwKrAzfvTfNDp/73BFRppjs9H7XaWzi0FtTQlaKPy0F4aqH/BTq5xXfcglqUFaj1loBAs2hIVaF3egx1U5xgxdGQmHSDr/gKTyyqcb3/36n0ETXR3C1Q30fXGzjnVUdS6I5vjs07O0xmb3nZ1f6O1HDhImL00lrgtYzXU6nGpvOTVtA/tvuvZ10EjXxBNeSOhsmb9DzukmlEn/k464nKfivmJvb7aerwgi0iqupum6IjWubTNMIc25GCsNTgt7SNgsyHsLk+6K8vlj7f1FP2iDhmYczH5eze850iTOPUU/K0iR1oc75e2rfkBoAGnAy7NUblnk0MbFTyXVp6MTqGUCoHo1BIb7uY5veF+RB6UraBW1ogY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
